### ISSUE TITLE
eval code 

### ISSUE THREAD

**Issue by ZSMZSM** [GZU-SAMLab/CDKM#1]
Thank you for your great work. Could you provide a complete evaluation code? I don't know how to evaluate the final mAP after I get the vg_instances_results.json .

**Comment by DengHY258** [comment]
Thank you for your reminder. There are two methods for calculating mAP：
1) The formal evaluation method (https://github.com/jcjohnson/densecap).
2) Rewrite Method 1 in Python (https://github.com/soloist97/densecap-pytorch).

**Comment by ZSMZSM** [comment]
> Thank you for your reminder. There are two methods for calculating mAP：
> 
> 1. The formal evaluation method (https://github.com/jcjohnson/densecap).
> 2. Rewrite Method 1 in Python (https://github.com/soloist97/densecap-pytorch).

Thank you so much for your response. I only replaced the (scores, boxes, text,) part in the evaluator.add_result(scores, boxes, text, target_boxes, target_text, img_id) code with the content from vg_instances_results.json. However, I got a very low mAP (0.004).Could you please tell me why this is the case?（Could it be a problem with the coordinates?） I would really appreciate your further response.
Alternatively, would it be possible for you to share the code that you edited? My email address is zsm2313388780@163.com

**Comment by ZSMZSM** [comment]
> Thank you for your reminder. There are two methods for calculating mAP：
> 
> 1. The formal evaluation method (https://github.com/jcjohnson/densecap).
> 2. Rewrite Method 1 in Python (https://github.com/soloist97/densecap-pytorch).

Hi Hongyu, Thank you for sharing your code .  but sorry to bother you again.
          Do the boxes format in your evaluation_file and the boxes format in GRiT's vg_instances_results.json match? I put the vg_instances_results.json from GRiT into the evaluation code you gave me but still got very low results. Can you share your evaluation_file? I want to find out what the key issue might be."

**Comment by ZSMZSM** [comment]
> Thank you for your reminder. There are two methods for calculating mAP：
> 
> 1. The formal evaluation method (https://github.com/jcjohnson/densecap).
> 2. Rewrite Method 1 in Python (https://github.com/soloist97/densecap-pytorch).

Hi Hongyu, Thank you for sharing your code . but sorry to bother you again.
Do the boxes format in your evaluation_file and the boxes format in GRiT's vg_instances_results.json match? I put the vg_instances_results.json from GRiT into the evaluation code you gave me but still got very low results.I've also tried other formats of boxes but none of them worked.  Can you share your evaluation_file? I want to find out what the key issue might be."
